### ISSUE TITLE
Enterprise-Registration-Data-of-Chinese-Mainland SQL

### ISSUE THREAD

**Issue by cheenwe** [cheenwe/pbs_dc#1]

**Comment by cheenwe** [comment]
链接:https://pan.baidu.com/s/1qBdNzOWLnoLPTf-nVGt-cg  密码:g4oy

**Comment by conpionchan** [comment]
![image](https://user-images.githubusercontent.com/55778802/86462775-bfc29f80-bd5e-11ea-8c0a-eab3f1f2e6b8.png)

**Comment by conpionchan** [comment]
在Navicat for MySQL上 运行SQL文件错误，如上图，请问是什么原因呢？
